import localFont from "next/font/local";
import { Do_Hyeon, Nanum_Brush_Script } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 👇 귀여운 폰트 2개 추가
const doHyeon = Do_Hyeon({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dohyeon",
});

const nanumBrush = Nanum_Brush_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-nanum-brush",
});

export const metadata = {
  title: "WAGIE - We Are Genius In Everything",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${doHyeon.variable} ${nanumBrush.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
